site_name: Parser
site_description: A multipart parser
site_url: https://www.multipart.fastapiexpert.com

theme:
  name: "material"
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - toc.follow

nav:
  - Home: index.md
  - Technical Decisions: technical_decisions.md
